# Generated by Django 3.1.3 on 2021-06-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLogicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio_usuario',
            name='status',
            field=models.CharField(choices=[('0', 'Aberto'), ('1', 'Concluido')], default='0', max_length=30, verbose_name='Status'),
        ),
    ]
