# Generated by Django 3.1.3 on 2021-06-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iLogicApp', '0002_auto_20210619_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio_usuario',
            name='pontos',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
    ]
